source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'bootstrap-sass', '~> 3.3.4'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'devise'
gem 'activeadmin', '~> 1.0.0.pre1'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'capistrano-rails', '~> 1.1.1'
  gem 'capistrano'
  gem 'web-console', '~> 2.0'
  # gem 'spring'
end

